### ISSUE TITLE
Create an endpoint to invite members 

### ISSUE THREAD

**Issue by kevinsmouts** [slackhq/slack-api-docs#22]
Could be a POST to `https://slack.com/api/users.invite` with params such as `email` `firstName` `lastName` and only email required.

I'm trying to get all my coworking space on Slack, and managing new invites on 10 different services is very time consuming. My objective is to automate all that.

What do you think?

**Comment by captn3m0** [comment]
:+1:

**Comment by ernesto-jimenez** [comment]
@kevinsmouts @captn3m0 there's already an undocumented API method that allows you to invite people in the mean time:
`https://$ORG.slack.com/api/users.admin.invite`

**Comment by kevinsmouts** [comment]
@ernesto-jimenez ok! I'm going to play around with it to see how it works. Thanks! When are you expecting to write the doc for this?

**Comment by ernesto-jimenez** [comment]
@kevinsmouts I don't work for Slack so I don't know what their plans are :)

Given it's undocumented they might as well deprecate the endpoint.

**Comment by nicolamattina** [comment]
This discussion is quite old, but this tutorial could be helpful. We had exactly the same problem when we wanted to launch our developers community on Slack because it does not have an automated option to manage invites. 

So we decided to integrate Slack APIs into Stamplay and created a web app. In this way our users can subscribe to our Slack Stamplayers Channel automagically and we do not have to manage invitations. At the same time, we receive a notification for every new user in the community... It works pretty well :)

If you are interested, here is a very quick tutorial on how to do it: https://blog.stamplay.com/launch-your-community-with-a-fully-automated-slack-signup-page/

**Comment by mccreath** [comment]
Hello, everyone! We have not documented the `users.admin.invite` method because it is still under development. Use it at your own risk. It's entirely possible that a future update will change functionality.

We are cognizant of the need for public, documented methods for user management and have started work on them. We don't have a firm timeline for them yet, but they are coming! Thanks for your patience. 

If you have further questions, feel free to send them to feedback@slack.com. We're going to continue monitoring the issues here, but response time will generally be faster at that email address.
