### ISSUE TITLE
Create users.admin.invite API doc

### ISSUE THREAD

**Issue by Neil-Ni** [slackhq/slack-api-docs#30]
I came across some usage for /api/users.admin.invite but I wasn't able to find the related doc on this api endpoint.

For example to invite a single-channel-access guest we could do: 
```
POST /api/users.admin.invite
{
    channels: channel_name
    token: token
    set_active: true
    email: email
    ultra_restricted: 1
}
```

**Comment by jtatum** [comment]
It is an undocumented endpoint. Slack does not document it intentionally. See e.g. https://twitter.com/slackapi/status/570323011338772480

**Comment by dblock** [comment]
Slack said they will not be updating that repo until they hire someone. We don't have to wait. I've pulled JSON files from https://github.com/slackhq/slack-api-docs into https://github.com/dblock/slack-api-ref, which I intend to maintain and kept JSON files only. We'll accept schema for undocumented methods, please feel free to contribute!

**Comment by mccreath** [comment]
Hello! The above comment from jtatum is correct. It is undocumented because it's still under development. If you use it, it is entirely possible that we'll make a change in the future that will change its behavior. We have started work on some user management methods that will be documented and supported. Don't have have a firm timeline for their release, but we recognize the need for them.

If you have further questions, feel free to send them to feedback@slack.com. We're going to continue monitoring the issues here, but response time will generally be faster at that email address.

**Comment by weisjohn** [comment]
@mccreath any updates on the documentation for creating users?

**Comment by mccreath** [comment]
@weisjohn Not yet. Still some issues to work out around user management in general.

**Comment by mattkast** [comment]
@mccreath Any updates on this??

**Comment by mccreath** [comment]
@mattkast Afraid not!

**Comment by derickbailey** [comment]
i'd really like to see this re-opened and officially supported.

i'm currently building an online community for javascript and i want to automate the invites for new members of my community, to my private slack for the community.

without official support for this, i'm stuck doing things manually :(

**Comment by mccreath** [comment]
Hi, @derickbailey. We working on a few things that will simplify the invite process. Stay tuned! 

We appreciate the feedback, and I'd encourage you to send this and any other platform to feedback@slack.com as well. We are listening to it.

**Comment by jeffmurchison** [comment]
Any update on user management?

**Comment by ClydeDroid** [comment]
For anyone still looking for information on this, @ErikKalkoken has a list of the undocumented API methods [here](https://github.com/ErikKalkoken/slackApiDoc).

**Comment by dblock** [comment]
I opened https://github.com/ErikKalkoken/slackApiDoc/issues/5. It would be great to contribute these in json format in some new folder in slack-api-ref and make them available in the auto-generated code in the ruby client.

**Comment by Unders0n** [comment]
Hello, is there any updates on this issue?
We're creating bot and we want it to have ability to add users. I've tried users.admin.invite method using bot oauth token (both app token, oath and bot tokens in "permissions" tab. I've tried all scopes, including team admin , no success, still getting "missing_scope" exception. Only workaround is working is i get old deprecated token of our team admin and pasted it in authorisation. What is the recommended way to solve our issue?

**Comment by ErikKalkoken** [comment]
@Unders0n the API method `users.admin.invite` works, but you will need an access token with admin rights to use it. A bot access token will most likely not work, since it is limited by design. Instead of using the "test token" you can also use the "full" access token that is created together with the bot access token during installation of your Slack app. However, I am pretty sure that your Slack app has to be installed by someone with the admin role for this work.
Please also see the current documentation of this method here: [users.admin.invite
](https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md)

**Comment by Unders0n** [comment]
@ErikKalkoken , yes thanks, we're using exactly this aproach. Just for info: full auth key of app not working either, even when installed by admin (atleast it was reinstalled by admin, we haven't tested brand new installation)
We're thinking of another issue now: i mentioned that we cant explicitly choose username for user. And we also can't configure some callback for this operation. I'm telling this 'cos without that i dont have ideas how we can fully automate this process, saving relevant info to DB.

**Comment by soundsgoodsofar** [comment]
+1. Our workaround for supporting slack communication is to create private channels for each thread on our platform, and then emulate messages having come from the other user.  This works to some extent, but it means that the party without a company slack account can't use slack as an actual guest.

**Comment by tansaku** [comment]
this endpoint seems to have stopped working for us recently :-(

**Comment by ErikKalkoken** [comment]
@tansaku no, still works fine. Checked again just now. So the issue must lie somewhere else. Also check with this the respective [documentation](https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md) with regards to correct token etc.

**Comment by tansaku** [comment]
thanks @ErikKalkoken good to know - we did just renew our token - we're posting to Slack via the documented API using it - I wonder what can be going on: here's our code:

https://github.com/AgileVentures/WebsiteOne/blob/develop/app/jobs/slack_invite_job.rb

**Comment by ErikKalkoken** [comment]
@tansaku sorry I don't know this programming. But I would suggest opening an question on Stackoverflow.com. Sure you find someone there who can help you.

**Comment by alxHenry** [comment]
@ErikKalkoken does this still work for you?

I'm getting a 200 and 'respone.ok === true', but no email in the invited email inbox and there is no trace of them on the 'pending invitations' page. 

I'm using a legacy auth token, maybe that's the issue?

**Comment by webdif** [comment]
Any news on this?

**Comment by ErikKalkoken** [comment]
the endpoint works fine. We use it every day. Those issues have most likely other causes.

**Comment by ErikKalkoken** [comment]
If you have any question / issue with this endpoint, please open a new issue at https://github.com/ErikKalkoken/slackApiDoc

this issue has been closed long ago

**Comment by intel352** [comment]
looks like @mccreath is still active for Slack, maybe he'll take pity and respond with an update, as his last update was almost 2 years ago.

**Comment by dblock** [comment]
Note that there's a new project, https://github.com/slackapi/slack-api-specs that seems to supersede this at this point, cc: @Roach maybe time to do something about this one?

**Comment by anjaneyach** [comment]
How to invite user using email via api ? Any news on this?

**Comment by ErikKalkoken** [comment]
As mentioned above you can invite users with this undocumented API method: https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md

**Comment by RobertasMurnikovas** [comment]
As I understand there still is no other way for creating a user in slack's API apart of this undocumented endpoint. My question is that, since this endpoint needs to have a legacy token in order to authenticate a user that is making a request to create a new user, is there an endpoint where i could firstly fetch my legacy token via API and then send the request to create a user. I cannot find any info regarding legacy tokens endpoints

**Comment by RobertasMurnikovas** [comment]
@ErikKalkoken

**Comment by soichih** [comment]
Does anyone know how to pre-set invited user's fullname? I tried first_name/last_name/name/fullname, but none of them seem to work.
