### ISSUE TITLE
documentation about team_disabled error is missing

### ISSUE THREAD

**Issue by ernesto-jimenez** [slackhq/slack-api-docs#40]

**Comment by dblock** [comment]
@ernesto-jimenez Slack said they will not be updating that repo until they hire someone. We don't have to wait. I've pulled JSON files from https://github.com/slackhq/slack-api-docs into https://github.com/dblock/slack-api-ref, which I intend to maintain and kept JSON files only. Would you like to contribute this fix?

**Comment by ernesto-jimenez** [comment]
Does it have Slack's blessing? Otherwise I would rather wait until they decide to maintain it.

They already have a Job opening for a dev rels, so it shouldn't take too long.

/cc @paulhammond @iamcal

**Comment by dblock** [comment]
It doesn't, but this is what I got from someone at slack:

![screen shot 2015-08-27 at 1 06 50 pm](https://cloud.githubusercontent.com/assets/542335/9527333/80734824-4cbc-11e5-9730-f5cb8cbdc600.png)

I am not holding my breath.

**Comment by dblock** [comment]
Plus if they decide to maintain and actually have someone on it, it I'll be happy to PR all changes. They *do* maintain the docs on https://api.slack.com, but that repo has clearly been private for a while - I imagine they have no real reason to maintain the JSON schema.

**Comment by ernesto-jimenez** [comment]
They just started building a bigger platform team recently, so they'll get there. I don't think spreading feedback across different repos would help, and spamming all issues/PR's can get annoying quickly.

**Comment by dblock** [comment]
Thanks @ernesto-jimenez, do what you feel is right.

**Comment by mccreath** [comment]
We are documenting this error as we speak, and it will be available in this repo in the next release!

**Comment by paulhammond** [comment]
Quick update on this one: in the end we didn't document this error. Instead we made the implementation match what the documentation says: if a team is disabled we'll now return an `account_inactive` error.  So you shouldn't see the `team_disabled` error any more.

Our thinking here is that as an API app developer it doesn't really matter to you if the account is inactive because the account was deleted or because the team was deleted, you're still going to show the same error message to your users.

Thanks for pointing this out!
